
lista_asignaturas = {"INF001": {"nombre" : "Fundamentos de las Bases de Datos", "nivel" : 1},
                    "INF002" : {"nombre" : "Diseño de Sistemas Informáticos" , "nivel" : 1},
                    "INF003" : {"nombre" : "Fundamentos de Hardware y Software" , "nivel" : 1},
                    "MAT001" : {"nombre" : "Taller Nivelación de Matemáticas" , "nivel" : 1},
                    "INF004" : {"nombre" : "Pensamiento Algorítmico" , "nivel" : 1},
                    "LEN001" : {"nombre" : "Taller de Habilidades Comunicativas" , "nivel" : 1},
                    "GEN001" : {"nombre" : "Bases Teóricas para la Diversidad" , "nivel" : 2},
                    "INF005" : {"nombre" : "Desarrollo de Bases de Datos" , "nivel" : 2},
                    "GEN002" : {"nombre" : "Herramientas Tecnológicas" , "nivel" : 2},
                    "MAT002" : {"nombre" : "Taller de Matemática II" , "nivel" : 2},
                    "INF006" : {"nombre" : "Programación Orientada a Objetos" , "nivel" : 2},
                    "INF007" : {"nombre" : "Taller de Redes Computacionales" , "nivel" : 2},
                    "INF008" : {"nombre" : "Desarrollo Backend" , "nivel" : 3},
                    "INF009" : {"nombre" : "Desarrollo de Bases de Datos I" , "nivel" : 3},
                    "EXT001" : {"nombre" : "Inglés Básico I" , "nivel" : 3},
                    "INF010" : {"nombre" : "Programación Front End" , "nivel" : 3},
                    "GEN003" : {"nombre" : "Pensamiento Innovador" , "nivel" : 3},
                    "INF011" : {"nombre" : "Sistemas Operativos" , "nivel" : 3},
                    "INF012" : {"nombre" : "Administración de Bases de Datos" , "nivel" : 4},
                    "INF013" : {"nombre" : "Desarrollo Fullstack" , "nivel" : 4},
                    "INF014" : {"nombre" : "Fundamentos de la Ciberseguridad" , "nivel" : 4},
                    "GEN004" : {"nombre" : "Herramientas para la Administración" , "nivel" : 4},
                    "EXT002" : {"nombre" : "Inglés Básico II" , "nivel" : 4},
                    "GEN005" : {"nombre" : "Programas para Análisis de Datos" , "nivel" : 4},
                    "PROF01" : {"nombre" : "Práctica Profesional" , "nivel" : 5},
                    "PROF02" : {"nombre" : "Taller de Integración" , "nivel" : 5}
}

lista_alumnos = [{"nombre" : "Claudio Becerra", "rut" : "186970268", "nivel" : 3, "asignaturas_inscritas" : []}, {"nombre" : "Javier Mancilla", "rut" : "111111111", "nivel" : 2, "asignaturas_inscritas" : []}]